export interface Asset {
  id: string
  icon: string
  name: string
  fullName: string
  category: 'stocks' | 'income' | 'bonds' | 'alternative' | 'special'
  riskLevel: 1 | 2 | 3 | 4 | 5
  horizon: string
  tagline: string
  history: string
  howItWorks: string
  risks: string[]
  stats: { label: string; value: string }[]
  howToInvest: string
  tip: string
  tickers?: string[]
  paysDividends?: boolean
  dividendYield?: string
}

export interface Account {
  id: string
  icon: string
  name: string
  fullName: string
  tag: string
  tagColor: string
  description: string
  pros: string[]
  cons: string[]
  limit: string
  bestFor: string
}

export interface Bias {
  id: string
  icon: string
  name: string
  ua: string
  description: string
  example: string
  fix: string
}

export const CATEGORIES = [
  { id: 'all', label: 'Всі' },
  { id: 'stocks', label: 'Акції' },
  { id: 'income', label: 'Дохідні' },
  { id: 'bonds', label: 'Облігації' },
  { id: 'alternative', label: 'Альтернативні' },
  { id: 'special', label: 'Спеціальні' },
] as const

export const ASSETS: Asset[] = [
  {
    id: 'sp500',
    icon: '📈',
    name: 'S&P 500',
    fullName: "Standard & Poor's 500",
    category: 'stocks',
    riskLevel: 3,
    horizon: '5+ років',
    tagline: '500 найбільших компаній США. Основа більшості портфелів у світі.',
    history: 'Створений у 1957 компанією Standard & Poor\'s. Першe значення: 49.74 пункти. Ідея: замість однієї компанії відстежувати 500 найбільших одночасно. До 2025 перетнув 5,500+. Уоррен Баффет заповів дружині: 90% в S&P 500 ETF після його смерті.',
    howItWorks: 'Зважений за ринковою капіталізацією — великі компанії займають більшу частку. Топ-10 (Apple, Microsoft, Nvidia, Amazon, Meta...) = ~35% індексу. Купуєте 1 акцію ETF → автоматично власник частки всіх 500 компаній пропорційно їх розміру.',
    risks: ['Може впасти 30–50% (2000, 2008, 2020)', 'Tech-концентрація — топ 10 = 35%', 'Відновлення після -38% (2008) зайняло 5–6 років', 'Тільки США — немає міжнародної диверсифікації'],
    stats: [
      { label: 'Середня дохідність (1957–2025)', value: '~10.5%/рік' },
      { label: 'Найгірший рік (2008)', value: '-38%' },
      { label: 'Найкращий рік (1995)', value: '+37.6%' },
      { label: '$10k вкладені у 2000', value: '~$57k у 2026' },
      { label: '$10k вкладені у 2010', value: '~$75k у 2026' },
      { label: '% років з позитивною дохідністю', value: '~74%' },
    ],
    howToInvest: 'Fidelity: FXAIX (0.015%) або FZROX (0%). Інші брокери: VOO (Vanguard 0.03%), IVV (BlackRock 0.03%), SPY (0.09%). Купуйте фіксовану суму щомісяця — не намагайтесь вгадати ринок.',
    tip: 'Баффет у 2007 поставив $1 млн що S&P 500 ETF переможе кошик хедж-фондів за 10 років. Виграв: S&P 500 +125%, хедж-фонди +36%.',
    tickers: ['FXAIX', 'FZROX', 'VOO'],
  },
  {
    id: 'nasdaq',
    icon: '💻',
    name: 'Nasdaq 100 / QQQ',
    fullName: 'Nasdaq-100 Technology Index',
    category: 'stocks',
    riskLevel: 4,
    horizon: '7+ років',
    tagline: 'S&P 500 на стероїдах. 100 найбільших non-financial компаній Nasdaq — майже весь tech.',
    history: 'Nasdaq як біржа заснована у 1971 — перша електронна фондова біржа у світі. Nasdaq-100 індекс запущений у 1985. QQQ ETF (найпопулярніший трекер) — 1999. Під час dot-com бульбашки впав на -83% (2000–2002) і відновився тільки у 2015. З 2009 по 2025 — один з найкращих активів у світі.',
    howItWorks: '100 найбільших нефінансових компаній на біржі Nasdaq. ~55% — технології: Apple, Microsoft, Nvidia, Meta, Alphabet, Amazon, Tesla. Більш концентрований і волатильніший ніж S&P 500, але і потенційно прибутковіший. Не включає банки та фінансові компанії.',
    risks: ['-83% під час dot-com (2000–2002)', 'Висока концентрація в tech — 55%', '-35% у 2022 через ріст ставок', 'Більш волатильний ніж S&P 500'],
    stats: [
      { label: 'Дохідність (2009–2025)', value: '~18%/рік' },
      { label: '2000–2002 (dot-com крах)', value: '-83%' },
      { label: '2022 (ріст ставок)', value: '-33%' },
      { label: '$10k вкладені у 2010', value: '~$120k у 2026' },
      { label: 'vs S&P 500 за 15 років', value: '+2× більше' },
    ],
    howToInvest: 'QQQ (Invesco, 0.20%) або QQQM (те саме але дешевше, 0.15%). На Fidelity також є ONEQ (Nasdaq Composite, ширший). Підходить як добавка до S&P 500 якщо хочете більше tech exposure — але не більше 20–30% портфелю.',
    tip: 'QQQ + S&P 500 = значне перекриття (обидва мають Apple, Microsoft і т.д.). Якщо хочете tech exposure — краще QQQ замість S&P 500, не на додаток.',
    tickers: ['QQQ', 'QQQM'],
  },
  {
    id: 'smallcap',
    icon: '🌱',
    name: 'Small Cap',
    fullName: 'Small Capitalization Stocks',
    category: 'stocks',
    riskLevel: 4,
    horizon: '7+ років',
    tagline: 'Менші компанії — більший потенціал росту і більший ризик. Доповнення до S&P 500.',
    history: '"Small cap premium" — феномен відомий з 1981 дослідження Ролфа Банца: дрібні компанії статистично перевищують великі в довгостроковій перспективі. Russell 2000 — основний індекс small cap (2,000 найменших компаній у Russell 3000). Останнє десятиліття large cap перевершував small cap через домінування tech гігантів.',
    howItWorks: 'Компанії з ринковою капіталізацією $300M–$2B. Менш "аналізовані" — більше шансів знайти недооцінену компанію. Більше представляють внутрішню економіку США (менше міжнародного доходу). Исторично outperform large cap на довгих горизонтах, але більш волатильні.',
    risks: ['Вищий ризик банкрутства окремих компаній', 'Менш ліквідні — ширший bid-ask spread', 'Більше постраждали у рецесіях', 'Останні 10 років відставали від large cap'],
    stats: [
      { label: 'Small cap premium (1927–2020)', value: '+2-3%/рік vs large cap' },
      { label: 'Russell 2000 (2022)', value: '-21%' },
      { label: 'Russell 2000 (2023)', value: '+17%' },
      { label: 'Expense ratio (кращих ETF)', value: '0.05%' },
    ],
    howToInvest: 'VB (Vanguard Small Cap, 0.05%), IJR (iShares S&P 600 Small Cap, 0.06%), SCHA (Schwab, 0.04%). Fidelity: FSSNX (0.025%). Рекомендована частка: 10–15% від equity портфелю.',
    tip: 'Small cap value (дрібні дешеві компанії) — найкращий performance factor за 100+ років досліджень. ETF: VBR (Vanguard Small Cap Value, 0.07%).',
    tickers: ['VB', 'IJR', 'VBR'],
  },
  {
    id: 'international',
    icon: '🌍',
    name: 'International / Emerging Markets',
    fullName: 'International & Emerging Market Stocks',
    category: 'stocks',
    riskLevel: 4,
    horizon: '7+ років',
    tagline: 'Решта світу за межами США. 60% світової економіки — не в американських акціях.',
    history: 'США займають ~60% світової ринкової капіталізації акцій, хоча американська економіка — ~25% світового ВВП. Emerging markets (Індія, Китай, Бразилія, ПАК, Індонезія) ростуть швидше але більш волатильні. Японія у 1989 впала на -80% і НЕ відновилась досі. Diversified international exposure — ключ до зниження home country bias.',
    howItWorks: 'Developed markets (Європа, Японія, Австралія, Канада) — стабільніші, нижчий потенціал. Emerging markets (Індія, Китай, Бразилія, В\'єтнам) — вищий ріст ВВП, більший ризик. Акції оцінені дешевше ніж US (P/E ~12–15 vs ~25 для S&P 500).',
    risks: ['Валютний ризик', 'Геополітичний ризик (Китай-Тайвань, Росія)', 'Слабший корпоративний governance', 'Відставали від S&P 500 останні 15 років (2010–2025)'],
    stats: [
      { label: 'MSCI World ex-US (20 років)', value: '~6%/рік' },
      { label: 'Emerging Markets (20 років)', value: '~7%/рік' },
      { label: 'Оцінка (P/E) vs S&P 500', value: '12–15 vs ~25' },
      { label: 'Частка світового ВВП', value: '75% — поза США' },
    ],
    howToInvest: 'FZILX (Fidelity Zero International, 0%). VXUS (Vanguard Total International, 0.07%). VEA (Developed markets). VWO (Emerging Markets, 0.08%). Оптимальна частка: 20–30% від equity.',
    tip: 'У 2000–2010 міжнародні акції ПЕРЕВЕРШИЛИ S&P 500. У 2010–2020 — навпаки. Ніхто не знає що буде наступним. Тримайте 20-30% міжнародних для справжньої диверсифікації.',
    tickers: ['FZILX', 'VXUS', 'VWO'],
  },
  {
    id: 'dividend',
    icon: '💸',
    name: 'Dividend ETFs',
    fullName: 'Dividend Income ETFs',
    category: 'income',
    riskLevel: 3,
    horizon: '5+ років',
    tagline: 'Пасивний дохід від компаній що регулярно платять дивіденди. Щоквартальні виплати.',
    paysDividends: true,
    dividendYield: '3–4%/рік',
    history: 'Дивіденди існують стільки ж скільки й акціонерні компанії (з 1600-х). "Dividend Aristocrats" — компанії що підвищують дивіденди 25+ років поспіль: Coca-Cola, Johnson & Johnson, Procter & Gamble. SCHD (Schwab US Dividend Equity) запущений у 2011 і став одним з найпопулярніших income ETF.',
    howItWorks: 'Компанії розподіляють частину прибутку акціонерам щоквартально. Dividend Yield = річні дивіденди / ціна акції. ETF типу SCHD відбирає компанії за: тривалістю виплат, темпом росту дивіденду, фінансовою стабільністю. Отримуєте кеш на рахунок 4 рази на рік — або реінвестуєте автоматично (DRIP).',
    risks: ['Компанії можуть скоротити або відмінити дивіденд (2020 COVID)', 'Менший потенціал росту ніж growth stocks', 'Дивіденди оподатковуються щороку в taxable рахунку', 'Більш чутливі до ставок (корпоративний борг дорожчає)'],
    stats: [
      { label: 'SCHD дивідендна дохідність', value: '~3.5%/рік' },
      { label: 'SCHD total return (2012–2025)', value: '~12%/рік' },
      { label: 'VIG (Dividend Growth) дохідність', value: '~1.7%/рік' },
      { label: 'Dividend Aristocrats (25+ років зростання)', value: '66 компаній (2025)' },
      { label: 'Dividend Kings (50+ років)', value: '54 компанії' },
    ],
    howToInvest: 'SCHD (Schwab, 0.06%) — найпопулярніший, баланс дохідності і якості. VIG (Vanguard Dividend Appreciation, 0.06%) — фокус на ріст дивіденду. VYM (Vanguard High Dividend, 0.06%) — вища поточна дохідність. ТРИМАЙТЕ В ROTH IRA — дивіденди не будуть щороку оподатковуватись.',
    tip: 'SCHD + VIG = ідеальна комбінація dividend ETF: SCHD дає вищу дохідність зараз, VIG — компанії що ростять дивіденд рік за роком (через 20 років VIG може платити більше).',
    tickers: ['SCHD', 'VIG', 'VYM'],
  },
  {
    id: 'coveredcall',
    icon: '📋',
    name: 'Covered Call ETFs',
    fullName: 'Covered Call / Option Income ETFs',
    category: 'income',
    riskLevel: 3,
    horizon: '3+ роки',
    tagline: 'Найвища поточна дохідність: 7–12%/рік. Продають опціони поверх акцій для генерації доходу.',
    paysDividends: true,
    dividendYield: '7–12%/рік',
    history: 'Стратегія covered calls існує десятиліттями, але ETF-форма популяризувалась у 2020–2022. JEPI (JPMorgan Equity Premium Income) запущений у 2020 і за 4 роки набрав $36+ млрд AUM — один з найшвидших ETF в історії. Популярний серед пенсіонерів і тих хто хоче пасивний дохід.',
    howItWorks: 'ETF тримає акції S&P 500, одночасно продаючи call-опціони на них. Покупець опціону платить премію (гроші) за право купити акції за певною ціною. Ця премія = ваш дохід. Щомісячні виплати. Compriomiss: ви отримуєте дохід, але обмежуєте upside (якщо ринок різко росте — ви відстаєте).',
    risks: ['Відстає від S&P 500 під час сильного росту', 'Складна структура — важко передбачити майбутню дохідність', 'Вищий expense ratio ніж пасивні ETF', 'Місячний дохід непостійний — залежить від волатильності'],
    stats: [
      { label: 'JEPI monthly distribution yield', value: '~7–9%/рік' },
      { label: 'JEPQ (Nasdaq version) yield', value: '~10–12%/рік' },
      { label: 'JEPI AUM (2025)', value: '$36+ млрд' },
      { label: 'JEPI vs S&P 500 (2022, падіння)', value: '-3% vs -18%' },
      { label: 'JEPI vs S&P 500 (2023, ріст)', value: '+9% vs +26%' },
    ],
    howToInvest: 'JEPI (JPMorgan, S&P 500 based, 0.35%) — найпопулярніший. JEPQ (JPMorgan, Nasdaq based, 0.35%) — вища дохідність, більший ризик. GPIQ, XYLD — альтернативи. Тримайте в IRA — місячні виплати оподатковуються як звичайний дохід.',
    tip: 'JEPI/JEPQ — не заміна S&P 500, а доповнення для тих хто хоче cash flow зараз. Молодим інвесторам з горизонтом 20+ років краще S&P 500 — більший total return. JEPI для пенсіонерів або "живу на дохід від портфеля".',
    tickers: ['JEPI', 'JEPQ'],
  },
  {
    id: 'reits',
    icon: '🏢',
    name: 'REITs',
    fullName: 'Real Estate Investment Trust',
    category: 'income',
    riskLevel: 3,
    horizon: '5+ років',
    tagline: 'Нерухомість без купівлі квартири. За законом платять 90%+ прибутку як дивіденди.',
    paysDividends: true,
    dividendYield: '3–6%/рік',
    history: 'REITs запровадив Конгрес США у 1960 — щоб звичайні люди могли інвестувати в комерційну нерухомість. Perший REIT на NYSE у 1965. Realty Income (O) платить дивіденди щомісяця без перерви з 1969 (56+ років). До 2025 ринок REITs США — $2.5+ трлн.',
    howItWorks: 'REIT — компанія, що володіє нерухомістю: склади, дата-центри, торгові центри, апартаменти, лікарні, вишки зв\'язку. За законом: 90%+ прибутку → акціонерам як дивіденди. Тому дохідність 3–6%/рік + потенційний ріст ціни. Дата-центри (Equinix, Digital Realty) ростуть через попит AI.',
    risks: ['Чутливі до ставок: ставки ростуть → REITs падають', '2022: FREL -26% через ріст ставок Fed', 'Офісні REITs постраждали від remote work', 'Дивіденди оподатковуються як звичайний дохід'],
    stats: [
      { label: 'Середня дохідність (1972–2025)', value: '~11.5%/рік' },
      { label: 'Дивідендна дохідність', value: '3–5%/рік' },
      { label: '2022 (найгірший рік)', value: '-26%' },
      { label: 'Realty Income (O) — дивіденди', value: '56+ років без перерви' },
    ],
    howToInvest: 'FREL (Fidelity, 0.084%), VNQ (Vanguard, 0.13%). Окремі REITs: O (Realty Income, щомісяця), AMT (American Tower, вишки), PLD (Prologis, склади), EQIX (Equinix, дата-центри). ОБОВ\'ЯЗКОВО: тримайте в Roth IRA.',
    tip: 'Data center REITs (EQIX, DLR, VKT) — найперспективніший REIT-сектор через ріст AI і хмарних сервісів. Попит на серверні потужності зростає швидше ніж будуються нові дата-центри.',
    tickers: ['FREL', 'VNQ', 'O'],
  },
  {
    id: 'preferred',
    icon: '🏅',
    name: 'Preferred Stock',
    fullName: 'Привілейовані акції',
    category: 'income',
    riskLevel: 3,
    horizon: '3+ роки',
    tagline: 'Гібрид між акцією і облігацією. Фіксований дивіденд, пріоритет при ліквідації.',
    paysDividends: true,
    dividendYield: '5–7%/рік',
    history: 'Preferred stock існує з 1800-х — компанії використовували для залучення капіталу не розводнюючи права звичайних акціонерів. Активно використовуються банками, utilities і REITs. Berkshire Hathaway Баффета любить preferred stock — під час кризи 2008 він інвестував у Goldman Sachs preferred з 10% дохідністю.',
    howItWorks: 'Пріоритет над звичайними акціями при: (1) виплаті дивідендів, (2) ліквідації компанії. Фіксований дивіденд (як купон облігації) — зазвичай 5–7%/рік. Ціна відносно стабільна (якщо компанія стабільна). Не має права голосу зазвичай. Менш відомі ніж звичайні акції.',
    risks: ['Ціна падає коли процентні ставки ростуть (як облігації)', 'Менш ліквідні ніж звичайні акції', 'Компанія може suspended dividend', 'Менший upside при рості компанії'],
    stats: [
      { label: 'Типова дохідність', value: '5–7%/рік' },
      { label: 'PFF (iShares Preferred) yield', value: '~6%' },
      { label: 'Correlation з ринком акцій', value: 'Нижча ніж common stock' },
    ],
    howToInvest: 'PFF (iShares, 0.46%) або PFFD (Global X, 0.23%) — найпростіший спосіб. Тримайте в IRA бо дивіденди оподатковуються як звичайний дохід. Складова частина "income ladder" разом з bonds і dividend stocks.',
    tip: 'Preferred stock = більший дохід ніж bonds але менший ніж high yield junk bonds, з кращим захистом ніж common stock. Ідеально для income-орієнтованого портфеля.',
    tickers: ['PFF', 'PFFD'],
  },
  {
    id: 'usbonds',
    icon: '🏦',
    name: 'US Bonds / Облігації',
    fullName: 'US Treasury & Bond Funds',
    category: 'bonds',
    riskLevel: 2,
    horizon: '1–10 років',
    tagline: 'Позика уряду і корпораціям з фіксованим доходом. Стабілізатор портфеля.',
    history: 'США випускають Treasury Bonds з 1790 для фінансування революційного боргу. 1980: ставка 10Y Treasury досягла 15.8% — рекорд. 2020: впала до 0.52% — антирекорд. 2022–2024: знову ~4–5%. Ринок облігацій США ~$50 трлн — більший за ринок акцій.',
    howItWorks: 'Позичаєте гроші уряду/компанії на термін. Отримуєте фіксований купон + повернення суми. Treasury Bills (1–12 міс), Notes (2–10 років), Bonds (20–30 років). КРИТИЧНО: ціна облігацій ПАДАЄ коли ставки РОСТУТЬ. 2022: Total Bond Market -13% через різкий підйом Fed.',
    risks: ['Ціна падає коли ставки ростуть', '2022: -13% (найгірший рік за 40 років)', 'Інфляційний ризик — купон може не покривати інфляцію', 'Корпоративні: кредитний ризик дефолту'],
    stats: [
      { label: 'US Treasury 10Y (2025)', value: '~4.3%' },
      { label: 'Total Bond Market (2022)', value: '-13%' },
      { label: 'Treasury 10Y максимум (1981)', value: '15.8%' },
      { label: 'Treasury 10Y мінімум (2020)', value: '0.52%' },
    ],
    howToInvest: 'ETF: FXNAX (Fidelity, 0.025%), BND (Vanguard), AGG. Short-term: SGOV (T-Bills 0-3M, ~5%), SCHO (1-3Y). Напряму: TreasuryDirect.gov без брокера. ТРИМАЙТЕ В IRA — генерують taxable income щороку.',
    tip: 'Short-term treasuries (SGOV, BIL) дають ~5% при мінімальному ризику — краще ніж більшість банків. Для cash що лежить більше 3 місяців — обов\'язково.',
    tickers: ['FXNAX', 'SGOV', 'BND'],
  },
  {
    id: 'tips',
    icon: '🛡️',
    name: 'TIPS',
    fullName: 'Treasury Inflation-Protected Securities',
    category: 'bonds',
    riskLevel: 2,
    horizon: '3–10 років',
    tagline: 'Облігації США з захистом від інфляції. Основна сума автоматично зростає з CPI.',
    history: 'TIPS введені Казначейством США у 1997 за прикладом UK (UK мала inflation-linked gilts з 1981). Першовипуск: $7 млрд 10-річних TIPS у лютому 1997. Стали надзвичайно популярними у 2021–2022 коли інфляція досягла 9% — попит зріс 3×.',
    howItWorks: 'Основна сума TIPS коригується по CPI (Consumer Price Index) щопівроку. Якщо інфляція 5%, ваші $10,000 стають $10,500 через рік. Купон (відсоток) нарахується на скориговану суму. При погашенні отримуєте БІЛЬШЕ з основних $10,000 якщо була інфляція. При дефляції — повертають оригінальну суму.',
    risks: ['Складне оподаткування — "phantom income" (платите податок на інфляційний приріст щороку, навіть не отримуючи кеш)', 'Реальна дохідність може бути негативною', 'Менш ліквідні ніж regular treasuries'],
    stats: [
      { label: 'Real yield (2025)', value: '~1.8-2.0%' },
      { label: 'Breakeven inflation rate', value: '~2.3%' },
      { label: 'TIPS у 2022 (рік інфляції)', value: '-12% (все одно впали!)' },
      { label: 'I-Bonds yield (2022, пік)', value: '9.62%' },
    ],
    howToInvest: 'ETF: SCHP (Schwab, 0.03%), VTIP (Vanguard Short-Term TIPS, 0.04%). Або I-Bonds напряму через TreasuryDirect.gov (до $10k/рік, кращі умови). ТРИМАЙТЕ В IRA щоб уникнути phantom income tax.',
    tip: 'I-Bonds — кращий варіант ніж TIPS для більшості: фіксована ставка + інфляційна надбавка, без phantom income, без падіння ціни. Мінус: ліміт $10k/рік і треба тримати мінімум 1 рік.',
    tickers: ['SCHP', 'VTIP'],
  },
  {
    id: 'munibonds',
    icon: '🏛️',
    name: 'Municipal Bonds',
    fullName: 'Муніципальні облігації (Muni Bonds)',
    category: 'bonds',
    riskLevel: 2,
    horizon: '2–10 років',
    tagline: 'Облігації штатів і міст. ФЕДЕРАЛЬНИЙ ПОДАТОК = 0%. Ідеально для високих брекетів.',
    history: 'Муніципальні облігації в США існують з 1800-х — міста і штати позичали для будівництва доріг, шкіл, водопроводів. Найвідоміший дефолт: Детройт (2013) — $18 млрд боргу. Пуерто-Рико (2016) — $73 млрд. Але більшість muni bonds дуже безпечні — особливо GO bonds (General Obligation).',
    howItWorks: 'Штат або місто позичає гроші для фінансування публічної інфраструктури. Відсотки звільнені від федерального податку і часто від податку штату (якщо ви живете в тому ж штаті). При 24% federal tax bracket: 4% muni = 5.26% taxable equivalent. При 37%: 4% muni = 6.35% taxable equivalent.',
    risks: ['Відсутність федерального захисту при дефолті (рідко, але буває)', 'Менш ліквідні ніж treasuries', 'AMT (Alternative Minimum Tax) може застосуватись', 'Зростання ставок = падіння ціни'],
    stats: [
      { label: 'Типова дохідність (10Y Muni)', value: '~3.5–4.0%' },
      { label: 'Tax-equivalent yield (24% bracket)', value: '~4.6–5.3%' },
      { label: 'Defaultrate (інвестиційний рейтинг)', value: '<0.1%/рік' },
      { label: 'Найбільший дефолт', value: 'Пуерто-Рико $73B (2016)' },
    ],
    howToInvest: 'ETF: MUB (iShares National Muni Bond, 0.07%), VTEB (Vanguard, 0.05%). Тільки має сенс у TAXABLE рахунку — бо в IRA і так немає податків, muni-пільга втрачається. При брекеті 22%+ — muni варті уваги.',
    tip: 'Muni bonds МАЮТЬ СЕНС тільки у taxable rахунку, і тільки якщо ваш federal tax bracket 22%+. Якщо ви у 12% bracket — звичайні treasury bonds дадуть більше after-tax.',
    tickers: ['MUB', 'VTEB'],
  },
  {
    id: 'corpbonds',
    icon: '🏗️',
    name: 'Corporate Bonds',
    fullName: 'Корпоративні облігації',
    category: 'bonds',
    riskLevel: 3,
    horizon: '2–7 років',
    tagline: 'Позика корпораціям. Вища дохідність ніж treasuries — але вищий кредитний ризик.',
    history: 'Корпоративні облігації — один з основних способів залучення капіталу для компаній (поряд з акціями). Ринок корпоративних облігацій США ~$10 трлн. Junk bonds (high yield) популяризував Майкл Мілкен у 1980-х через Drexel Burnham Lambert — і він же ж і розв\'язав crisis. 2008: корпоративні спреди досягли максимумів — HY bonds давали 20%+ дохідність (але були дуже ризикованими).',
    howItWorks: 'Два сегменти: (1) Investment Grade (рейтинг BBB- і вище): Apple, Microsoft, AT&T — відносно безпечні, дохідність +0.5-1.5% vs treasuries. (2) High Yield / Junk Bonds (BB і нижче): менш надійні компанії, дохідність +3-8% vs treasuries, але значно вищий ризик дефолту.',
    risks: ['Кредитний ризик — компанія може дефолтнути', 'High yield у кризу падають як акції (-25% у 2008)', 'Процентний ризик аналогічний treasuries', 'Менш ліквідні ніж treasuries'],
    stats: [
      { label: 'IG Corporate spread vs Treasury', value: '+0.8-1.5%' },
      { label: 'High Yield spread vs Treasury', value: '+3-6%' },
      { label: 'HY default rate (avg нормальний рік)', value: '2-3%/рік' },
      { label: 'HY default rate (2009, криза)', value: '~12%' },
    ],
    howToInvest: 'Investment Grade: LQD (iShares, 0.14%), VCIT (Vanguard, 0.04%). High Yield: HYG (iShares, 0.48%), JNK (SPDR). ТРИМАЙТЕ В IRA — корпоративні bonds генерують taxable income. Для більшості портфелів: investment grade > high yield.',
    tip: 'High Yield bonds у кризу корелюють з акціями (обидва падають) — тобто не дають справжньої диверсифікації. Для балансу ризику краще investment grade або treasuries.',
    tickers: ['LQD', 'VCIT', 'HYG'],
  },
  {
    id: 'moneymarket',
    icon: '💵',
    name: 'Money Market',
    fullName: 'Money Market Fund',
    category: 'bonds',
    riskLevel: 1,
    horizon: '0–2 роки',
    tagline: 'Краще банківського рахунку. ~4.4%/рік. Ідеально для cash та emergency fund.',
    history: 'Перший Money Market фонд — Reserve Fund — запущений у 1971. 2008: Reserve Fund "broke the buck" — пай впав нижче $1, спричинив паніку. Після цього SEC ввела суворі регуляції. SPAXX (Fidelity) — один з найбільших у світі, $300+ млрд AUM.',
    howItWorks: 'Інвестує в US Treasury Bills, repo agreements, commercial paper. Ціна = завжди $1.00. Дохід щомісяця у вигляді нових паїв. На Fidelity: SPAXX автоматично "підбирає" кеш що лежить без роботи — ~4.4%/рік без жодних дій з вашого боку.',
    risks: ['НЕ застрахований FDIC (на відміну від банку)', 'Дохідність падає якщо Fed знижує ставки', 'Теоретичний ризик "breaking the buck" — дуже малоймовірно'],
    stats: [
      { label: 'SPAXX дохідність (2025)', value: '~4.4%/рік' },
      { label: 'Vs середній банк', value: '4.4% vs 0.5%' },
      { label: 'На $34k emergency fund за рік', value: '+$1,360 різниці' },
      { label: 'Ліквідність', value: 'Миттєва' },
    ],
    howToInvest: 'На Fidelity: вже є автоматично (SPAXX). Для emergency fund: Marcus by Goldman Sachs або Ally Bank HYSA — ~4.5-5%, FDIC застрахований. SGOV ETF (T-Bills) — трохи вища дохідність, можна і в IRA.',
    tip: 'Якщо $34k emergency fund лежить у звичайному банку при 0.5% — переведіть у HYSA. 15 хвилин роботи = +$1,360/рік гарантовано, без жодного ризику.',
    tickers: ['SPAXX', 'SGOV'],
  },
  {
    id: 'gold',
    icon: '🥇',
    name: 'Gold / Золото',
    fullName: 'Precious Metal — Gold',
    category: 'alternative',
    riskLevel: 2,
    horizon: '3+ роки',
    tagline: '5000 років як сховище цінності. Захист від інфляції та геополітичних криз.',
    history: 'Золото як гроші — понад 5,000 років. Золотий стандарт США існував до 1971 коли Ніксон "закрив золоте вікно". 2000: $280/oz → 2011: $1,900 → 2020: $2,067 → 2025: $2,900+. Центробанки у 2023 купили 1,037 тонн — абсолютний рекорд. Причина: де-доларизація і геополітична нестабільність.',
    howItWorks: 'Фізичний актив без грошового потоку — не платить дивідендів. Ціна визначається: попитом центробанків, геополітикою, інфляцією, силою долара. Зростає під час: інфляції, банківських криз, геополітичної напруги. ETF на золото зберігають фізичне золото у сховищах (Лондон, Нью-Йорк).',
    risks: ['Не генерує дохід', 'Короткострокова волатильність -20-30%', 'Поведінка непередбачувана у короткостроці'],
    stats: [
      { label: 'Дохідність 2000–2025', value: '~10%/рік' },
      { label: '2000: $280/oz → 2025', value: '~$2,900/oz (×10.4)' },
      { label: '2022 (рік падіння ринків)', value: '-0.3%' },
      { label: 'Центробанки куп. 2023', value: '1,037 т — рекорд' },
    ],
    howToInvest: 'GLDM (State Street, 0.10%) або IAU (iShares, 0.25%) — найкраще. GLD (0.40%) — менш вигідний. Оптимальна частка: 5–10%.',
    tip: '2008: акції -38%, золото +5%. 2022: акції -18%, золото -0.3%. 5-10% золота в портфелі суттєво знижує волатильність без великих втрат дохідності.',
    tickers: ['GLDM', 'IAU'],
  },
  {
    id: 'commodities',
    icon: '🛢️',
    name: 'Commodities',
    fullName: 'Сировинні товари (нафта, срібло, с/г)',
    category: 'alternative',
    riskLevel: 4,
    horizon: '3+ роки',
    tagline: 'Нафта, природний газ, срібло, мідь, зерно. Захист від інфляції, але висока волатильність.',
    history: 'Ф\'ючерсна торгівля сировиною виникла у Японії у 1700-х (рис). Чиказька товарна біржа (CBOT) заснована у 1848. Нафта торгується як ф\'ючерс з 1983 на NYMEX. У квітні 2020 нафта WTI впала до -$37/барель (від\'ємне значення!) через COVID і переповнені сховища.',
    howItWorks: 'Сировина: енергоресурси (нафта, газ), метали (золото, срібло, мідь), с/г (пшениця, кукурудза, соя). ETF на commodities тримають ф\'ючерсні контракти або фізичний товар. Срібло: промислове + ювелірне + інвестиційне використання. Мідь — "доктор Мідь" передбачає економіку.',
    risks: ['Дуже висока волатильність', 'Contango problem у ф\'ючерсних ETF (щоразу купують дорожче)', 'Немає внутрішнього доходу', 'Нафта: геополітика, OPEC рішення'],
    stats: [
      { label: 'DJP (Bloomberg Commodity) 10 років', value: '~1-2%/рік' },
      { label: 'Срібло (2020 → 2025)', value: '×2.5' },
      { label: 'Нафта WTI (апрель 2020)', value: '-$37/барель (від\'ємна!)' },
      { label: 'Мідь (2020 → 2025)', value: '×2' },
    ],
    howToInvest: 'Диверсифікована сировина: DJP (Bloomberg), GSG (iShares). Срібло окремо: SLV (iShares) або SIVR. Мідь: CPER. Нафта: USO — але contango проблема. Краще через акції нафтових компаній (XOM, CVX) ніж прямі commodity ETF.',
    tip: 'Commodities ETF страждають від "contango roll" — щомісяця продають дешевший ближній ф\'ючерс і купують дорожчий далекий. За 5 років можна мати правильний прогноз по нафті але все одно бути мінус. Акції нафтових компаній краще.',
    tickers: ['GLD', 'SLV', 'DJP'],
  },
  {
    id: 'crypto',
    icon: '₿',
    name: 'Crypto / Bitcoin',
    fullName: 'Cryptocurrency — Bitcoin, Ethereum',
    category: 'alternative',
    riskLevel: 5,
    horizon: '4+ роки (тільки те що готові втратити)',
    tagline: 'Найвищий потенціал. Найвищий ризик. Просадки -80% — абсолютна норма.',
    history: 'Bitcoin створений у 2008 Satoshi Nakamoto. Перша транзакція — 2009. 2010: 2 піци за 10,000 BTC (~$1 млрд сьогодні). 2017 пік: $19k → 2018 дно: $3k (-83%). 2021 пік: $69k → 2022 дно: $15.5k (-77%). 2024–2025: $100k+. FTX крах (2022) — $32 млрд втрачено.',
    howItWorks: 'Decentralized digital currency. Максимум 21 млн BTC. Кожні ~4 роки halving — нова емісія зменшується вдвічі. Ethereum — платформа смарт-контрактів (DeFi, NFT, dApps). Altcoins (99%+) — в основному спекуляція без фундаменталу.',
    risks: ['-80% просадки тричі (2011, 2018, 2022)', 'Ризик бірж — Mt.Gox, FTX (люди втратили все)', 'Регуляторний ризик', 'Немає внутрішньої вартості'],
    stats: [
      { label: 'BTC 2010 → 2025', value: '$0.08 → $100k (×1.25 млн)' },
      { label: 'Максимальна просадка 2022', value: '-77%' },
      { label: '$10k у грудні 2017 (пік)', value: '~$55k у 2026' },
      { label: '$10k у листопаді 2022 (дно)', value: '~$62k у 2026' },
    ],
    howToInvest: 'Fidelity: FBTC (Bitcoin ETF, 0.25%). Або Coinbase/Kraken напряму. НЕ тримайте >1 місяця на біржі. Hardware wallet: Ledger, Trezor. Максимум 5–10% портфелю. Тільки DCA.',
    tip: 'Якщо купили будь-коли і тримали 4+ роки — у 95%+ випадків були в плюсі. Але -80% психологічно витримати майже неможливо для більшості людей. Перевірте себе: $2,000 → $400 — ви не продасте?',
    tickers: ['FBTC'],
  },
  {
    id: 'targetdate',
    icon: '🎯',
    name: 'Target Date Funds',
    fullName: 'Target Date / Lifecycle Funds',
    category: 'special',
    riskLevel: 2,
    horizon: '10+ років (до пенсії)',
    tagline: '"Вклав і забув" стратегія. Автоматично ребалансується — більше акцій зараз, більше bonds з часом.',
    history: 'Перший target date fund запущений у 1994 компанією Wells Fargo. Після Pension Protection Act 2006 стали default option у 401(k) планах — що різко збільшило їх популярність. До 2025: $3.5+ трлн в target date funds у США. Vanguard Target Retirement series — найпопулярніша лінійка.',
    howItWorks: 'Вибираєте рік виходу на пенсію (2040, 2045, 2050...) → фонд автоматично: зараз 90% акції + 10% бонди → з роками поступово зміщується до консервативного (40% акції + 60% бонди до пенсії). Це "glide path". Вам не треба нічого робити.',
    risks: ['Вищий expense ratio ніж прості index ETF', 'Glide path може не відповідати вашому ризик-профілю', 'Не оптимальний для taxable рахунків (генерує distributions)'],
    stats: [
      { label: 'Vanguard TDF expense ratio', value: '0.08%' },
      { label: 'Fidelity Freedom TDF', value: '0.12%' },
      { label: 'AUM Target Date Funds США', value: '$3.5+ трлн' },
      { label: '% 401(k) що використовують TDF', value: '~80%' },
    ],
    howToInvest: 'Vanguard Target Retirement 2050 (VFIFX), Fidelity Freedom Index 2050 (FDEWX). Ідеально для 401(k) якщо не хочете думати про allocation. НЕ ідеально для taxable рахунків.',
    tip: 'Target Date Fund — ідеальний варіант для 401(k) якщо ви не хочете займатись ребалансуванням. Але якщо ваш горизонт довший ніж дата фонду — розгляньте пізніший рік (2060 замість 2045 навіть якщо виходите у 2045).',
    tickers: ['VFIFX', 'FDEWX'],
  },
  {
    id: 'leveraged',
    icon: '⚠️',
    name: 'Leveraged ETFs',
    fullName: 'Leveraged & Inverse ETFs — НЕБЕЗПЕЧНО',
    category: 'special',
    riskLevel: 5,
    horizon: 'НЕ для довгострокових! Тільки короткостроково',
    tagline: '⚠️ TQQQ = Nasdaq ×3. SOXL = Semiconductors ×3. Не для звичайних інвесторів.',
    history: 'Перші leveraged ETF запущені ProShares у 2006. TQQQ (Nasdaq ×3 bull) і SQQQ (Nasdaq ×3 bear) — найпопулярніші. 2022: TQQQ впав -79% за рік. 2023: TQQQ виріс +234%. Багато людей втратили пенсійні заощадження тримаючи ці ETF довгостроково.',
    howItWorks: 'Щодня перезбалансовуються до досягнення ×2 або ×3 від денної прибутковості ІНДЕКСУ. Через "volatility decay" — при нестабільному ринку навіть якщо індекс повернувся до початку, leveraged ETF буде НИЖЧЕ. 10% up + 10% down ≠ 0% (це -1%). Для ×3 ефект набагато гірший.',
    risks: ['TQQQ 2022: -79% за рік', 'Volatility decay знищує вартість у volatile ринку', 'НЕ підходять для "buy and hold"', '2× і 3× збитки НЕ компенсуються 2× і 3× прибутками'],
    stats: [
      { label: 'TQQQ (2022, ×3 Nasdaq)', value: '-79%' },
      { label: 'TQQQ (2023, ×3 Nasdaq)', value: '+234%' },
      { label: 'SOXL (2022, ×3 Semiconductor)', value: '-90%' },
      { label: 'Volatility decay ефект', value: 'Реальний при vol >20%' },
    ],
    howToInvest: 'НЕ рекомендується для довгострокових інвесторів. Якщо все ж хочете — тільки з повним розумінням volatility decay, тільки гроші що готові повністю втратити, тільки короткострокові тактичні позиції.',
    tip: 'Warren Buffett: "Ніколи не купуйте те, що не розумієте." Якщо не розумієте volatility decay і daily rebalancing — не купуйте leveraged ETF. Для довгострокового інвестування вони руйнівні.',
    tickers: ['TQQQ', 'SOXL'],
  },
  {
    id: 'stocks',
    icon: '🏭',
    name: 'Individual Stocks',
    fullName: 'Окремі акції компаній',
    category: 'stocks',
    riskLevel: 4,
    horizon: '5+ років',
    tagline: 'Власність частки компанії. Вищий потенціал і вищий ризик порівняно з ETF.',
    history: 'Перша акціонерна компанія — Голландська Ост-Індська (VOC), 1602. NYSE заснована під деревом Buttonwood у Нью-Йорку в 1792. Apple 2000: $0.50 → 2025: $220 (×440). Enron 2000: $90 → 2001: $0.',
    howItWorks: '1 акція = частка власності. Прибуток: (1) ріст ціни, (2) дивіденди. Ключові метрики: P/E (ціна/прибуток), Revenue Growth, Free Cash Flow, Debt/Equity, "Moat" (конкурентна перевага). Ви конкуруєте з тисячами аналітиків і алгоритмами що аналізують ту ж інформацію.',
    risks: ['Компанія може збанкрутувати', 'Концентрований ризик — 1 ставка', '90% активних фондів програють S&P 500 за 15+ років', 'Емоційні рішення'],
    stats: [
      { label: 'Apple (AAPL) 2000 → 2025', value: '×440' },
      { label: 'Enron 2000 → 2001', value: '$90 → $0' },
      { label: '% активних фондів що б\'ють S&P 500 (15р)', value: '~10%' },
    ],
    howToInvest: 'Не більше 10–20% портфелю. Решта — ETF. Fidelity: безкоштовний Stock Screener + Research від 10+ аналітиків. Правило Баффета: "Купуй компанії що розумієш і тримай 10+ років."',
    tip: 'Навіть Баффет радить більшості купити S&P 500 ETF. Хочете "погратись" — виділіть окремий play money рахунок (5–10%) і не мішайте з основними заощадженнями.',
  },
]

export const ACCOUNTS: Account[] = [
  {
    id: 'roth',
    icon: '🌟',
    name: 'Roth IRA',
    fullName: 'Roth Individual Retirement Account',
    tag: 'НАЙКРАЩИЙ ДЛЯ БІЛЬШОСТІ',
    tagColor: '#22c55e',
    description: 'Вкладаєте ПІСЛЯ сплати податків. Весь ріст і виведення після 59½ — повністю без податків назавжди.',
    pros: ['Ріст і виведення після 59½ — 0% податків', 'Внески (не заробіток) можна виводити будь-коли без штрафів', 'Немає обов\'язкових RMD — гроші ростуть скільки хочете', 'Ідеально передати нащадкам'],
    cons: ['Ліміт доходу: >$161k (single) або >$240k (married) — не можна вносити прямо', 'Ліміт: $7,000/рік ($8,000 якщо 50+)', 'Штраф 10% за дострокове виведення ЗАРОБІТКУ до 59½'],
    limit: '$7,000/рік ($8,000 якщо 50+)',
    bestFor: 'Всі хто очікує вищий або однаковий брекет на пенсії. Молодь — особливо. Якщо дохід перевищує ліміт — Backdoor Roth.',
  },
  {
    id: 'traditional',
    icon: '🏛',
    name: 'Traditional IRA',
    fullName: 'Traditional Individual Retirement Account',
    tag: 'ЗНИЖУЄ ПОДАТКИ ЗАРАЗ',
    tagColor: '#3b82f6',
    description: 'Вкладаєте ДО сплати податків. Знижує оподатковуваний дохід зараз. Платите при виведенні на пенсії.',
    pros: ['Знижує taxable income зараз (якщо зараз у вищому брекеті)', 'Немає ліміту доходу для внеску', 'Ріст — без щорічних податків'],
    cons: ['Платите податки при виведенні на пенсії', 'RMD обов\'язкові з 73 років', 'Штраф 10% за виведення до 59½'],
    limit: '$7,000/рік ($8,000 якщо 50+)',
    bestFor: 'Якщо зараз у вищому брекеті ніж очікуєте на пенсії. Або як базис для Backdoor Roth конвертації.',
  },
  {
    id: '401k',
    icon: '🏢',
    name: '401(k) / Roth 401(k)',
    fullName: 'Employer-Sponsored Retirement Plan',
    tag: 'БЕЗКОШТОВНІ ГРОШІ ВІД РОБОТОДАВЦЯ',
    tagColor: '#8b5cf6',
    description: 'Пенсійний план через роботодавця. Головна перевага: employer match — роботодавець додає свої гроші до ваших. Це миттєвий 50–100% дохід.',
    pros: ['Employer match — 50–100% від ваших внесків (безкоштовно!)', 'Ліміт набагато вищий ніж IRA', 'Є Roth 401(k) варіант — ріст без податків', 'Автоматичні відрахування з зарплати'],
    cons: ['Обмежений вибір фондів (тільки те що пропонує план)', 'Штраф 10% за виведення до 59½', 'При зміні роботи — rollover в IRA'],
    limit: '$23,500/рік (+ $7,500 якщо 50+)',
    bestFor: 'Мінімум — внести стільки щоб отримати ПОВНИЙ employer match. Це найпростіший 50–100% дохід. Потім — Roth IRA → решта 401k.',
  },
  {
    id: 'sep',
    icon: '💼',
    name: 'SEP-IRA',
    fullName: 'Simplified Employee Pension IRA',
    tag: 'ДЛЯ SELF-EMPLOYED',
    tagColor: '#f59e0b',
    description: 'Для самозайнятих і малих бізнесів. Найпростіший пенсійний план для фрілансерів. Величезні ліміти.',
    pros: ['Ліміт $69,000/рік (25% від net self-employment income)', 'Дуже простий у відкритті і адмініструванні', 'Внески знижують taxable income', 'Можна відкрити навіть до квітня наступного року для поточного податкового року'],
    cons: ['Якщо є наймані працівники — треба і їм відкривати SEP-IRA', 'Тільки Traditional варіант (не Roth)', 'Немає catch-up contribution'],
    limit: '$69,000/рік або 25% від net income (менше з двох)',
    bestFor: 'Фрілансери, contractors, sole proprietors без найманих працівників. Якщо є працівники — Solo 401(k) або SIMPLE IRA.',
  },
  {
    id: 'solo401k',
    icon: '🚀',
    name: 'Solo 401(k)',
    fullName: 'Individual / One-Participant 401(k)',
    tag: 'НАЙКРАЩИЙ ДЛЯ ФРІЛАНСЕРІВ',
    tagColor: '#10b981',
    description: 'Для self-employed без найманих працівників. Поєднує employee і employer contributions — найвищий ефективний ліміт.',
    pros: ['Внески як employee ($23,500) + як employer (25% від доходу) = до $69,000/рік', 'Є Roth Solo 401(k) варіант', 'Loans до 50% балансу або $50k', 'Відкривається легко через Fidelity або Vanguard'],
    cons: ['Тільки для self-employed БЕЗ найманих працівників', 'Треба закрити якщо наймаєте людей', 'Більш складний у адмініструванні ніж SEP-IRA'],
    limit: 'До $69,000/рік (employee + employer contributions)',
    bestFor: 'Фрілансери і self-employed з вищим доходом. При доході $100k+ Solo 401(k) дає більший ліміт ніж SEP-IRA.',
  },
  {
    id: '403b',
    icon: '🎓',
    name: '403(b)',
    fullName: '403(b) Tax-Sheltered Annuity Plan',
    tag: 'ДЛЯ НОН-ПРОФІТІВ І ОСВІТИ',
    tagColor: '#06b6d4',
    description: 'Аналог 401(k) але для вчителів, лікарів у public hospitals, некомерційних організацій і університетів.',
    pros: ['Аналогічний 401(k) за функціями і лімітами', 'Деякі плани мають додаткові "15-year catch-up" contributions', 'Зазвичай TIAA-CREF або Vanguard — хороші фонди'],
    cons: ['Обмежений вибір фондів', 'Деякі 403(b) мають складні аннуїтетні продукти з високими комісіями', 'Треба перевіряти expense ratios фондів у плані'],
    limit: '$23,500/рік (+ $7,500 якщо 50+)',
    bestFor: 'Вчителі K-12, співробітники університетів, лікарі у public health. Якщо ваш роботодавець пропонує — максимізуйте так само як 401(k).',
  },
  {
    id: 'simple',
    icon: '🏪',
    name: 'SIMPLE IRA',
    fullName: 'Savings Incentive Match Plan for Employees',
    tag: 'ДЛЯ МАЛОГО БІЗНЕСУ',
    tagColor: '#84cc16',
    description: 'Пенсійний план для малого бізнесу (до 100 співробітників). Простіший ніж 401(k) у адмініструванні.',
    pros: ['Роботодавець зобов\'язаний матчити (2% або 3%)', 'Простіший і дешевший ніж 401(k) для бізнесу', 'Вищий ліміт ніж IRA'],
    cons: ['Нижчий ліміт ніж 401(k)', 'Штраф 25% (!) за виведення протягом перших 2 років', 'Тільки для компаній до 100 співробітників'],
    limit: '$16,500/рік (+ $3,500 якщо 50+)',
    bestFor: 'Малий бізнес що не може собі дозволити повний 401(k) план. Або співробітники малого бізнесу.',
  },
  {
    id: 'taxable',
    icon: '📊',
    name: 'Taxable Brokerage',
    fullName: 'Taxable Investment Account',
    tag: 'МАКСИМАЛЬНА ГНУЧКІСТЬ',
    tagColor: '#f59e0b',
    description: 'Звичайний брокерський рахунок без обмежень. Виводьте будь-коли без штрафів.',
    pros: ['Без лімітів внеску', 'Виводьте будь-коли без штрафів', 'Tax-loss harvesting можливість', 'Повний вибір активів'],
    cons: ['Дивіденди і відсотки оподатковуються щороку (форма 1099)', 'Продаж з прибутком = capital gains tax', 'Немає податкових пільг'],
    limit: 'Без обмежень',
    bestFor: 'Після максимізації IRA і 401(k). Або якщо гроші потрібні до 59½. Тримайте тут: growth ETF (FZROX, FZILX, GLDM) — вони майже не генерують taxable income.',
  },
  {
    id: 'utma',
    icon: '👶',
    name: 'UTMA / Custodial',
    fullName: 'Uniform Transfers to Minors Act',
    tag: 'ДЛЯ ДІТЕЙ (ГНУЧКО)',
    tagColor: '#ec4899',
    description: 'Інвестиційний рахунок для дитини. Ви управляєте поки дитині не виповниться 18–21. Потім юридично її гроші.',
    pros: ['Перші $1,300 доходу — без податків', 'Без обмежень на мету (на відміну від 529)', 'Довгий горизонт = 100% акції виправдані'],
    cons: ['"Kiddie tax" — дохід >$2,600 оподатковується за ставкою батьків', 'Гроші ЮРИДИЧНО переходять дитині в 18–21', 'Може вплинути на FAFSA'],
    limit: 'Без річних лімітів (gift tax при >$18k/рік)',
    bestFor: 'Стартовий капітал для дитини без прив\'язки до освіти. 17+ років горизонт → 80% FZROX + 20% FZILX.',
  },
  {
    id: '529',
    icon: '📚',
    name: '529 Plan',
    fullName: 'Qualified Tuition Savings Plan',
    tag: 'НА ОСВІТУ (ПІЛЬГОВО)',
    tagColor: '#06b6d4',
    description: 'Рахунок з податковими пільгами для освіти. Ріст і виведення без федеральних податків — якщо на освіту.',
    pros: ['Ріст без федеральних податків (якщо на кваліфіковані освітні витрати)', 'Деякі штати дають додатковий state tax deduction', 'З 2024: до $35k невикористаних грошей можна перевести в Roth IRA (lifetime)'],
    cons: ['Штраф 10% + податки якщо не на освіту', 'Обмежений вибір інвестицій', 'Вплив на FAFSA'],
    limit: 'Без річних лімітів (gift tax при >$18k/рік)',
    bestFor: 'Якщо впевнені що дитина піде у вищу освіту. Якщо ні — UTMA гнучкіший варіант.',
  },
  {
    id: 'coverdell',
    icon: '✏️',
    name: 'Coverdell ESA',
    fullName: 'Coverdell Education Savings Account',
    tag: 'ОСВІТА K-12 + КОЛЕДЖ',
    tagColor: '#8b5cf6',
    description: 'Альтернатива 529: покриває не тільки коледж але і K-12 приватну школу. Але дуже малий ліміт.',
    pros: ['Покриває K-12 приватні школи (529 — тільки до $10k/рік на K-12)', 'Більший вибір інвестицій ніж у 529', 'Ріст без податків на кваліфіковані витрати'],
    cons: ['ДУЖЕ малий ліміт: $2,000/рік на дитину', 'Ліміт доходу: >$110k (single) або >$220k (married) — не можна вносити', 'Треба використати до 30 років дитини'],
    limit: '$2,000/рік на дитину',
    bestFor: 'Якщо плануєте відправити дитину в приватну школу K-12. Використовуйте разом з 529 (відкрийте обидва).',
  },
  {
    id: 'hsa',
    icon: '🏥',
    name: 'HSA',
    fullName: 'Health Savings Account',
    tag: 'ПОТРІЙНА ПІЛЬГА',
    tagColor: '#10b981',
    description: 'Технічно найефективніший рахунок в США: ТРИ податкові пільги одночасно.',
    pros: ['Внески знижують taxable income', 'Ріст без податків', 'Виведення на медвитрати — без податків', 'Після 65: виводьте на будь-що як Traditional IRA', 'Rollover — гроші ростуть необмежено'],
    cons: ['Тільки для тих хто має HDHP (High-Deductible Health Plan)', 'До 65: тільки медичні витрати (без цього — штраф 20%)'],
    limit: '$4,300 (individual) / $8,550 (family)',
    bestFor: 'Якщо у вас HDHP — максимізуйте HSA в першу чергу. Стратегія: платіть медичні рахунки зараз з кишені, зберігайте чеки, виводьте через 20 років без податків.',
  },
  {
    id: 'backdoor',
    icon: '🚪',
    name: 'Backdoor Roth IRA',
    fullName: 'Backdoor Roth Conversion Strategy',
    tag: 'ДЛЯ HIGH EARNERS',
    tagColor: '#f97316',
    description: 'Легальна стратегія для людей з доходом вище ліміту Roth IRA. Внести в Traditional IRA → конвертувати в Roth.',
    pros: ['Дозволяє Roth IRA навіть при доході $300k+', 'Легально і широко використовується', 'Всі переваги Roth IRA після конвертації'],
    cons: ['Pro-rata rule — якщо є pre-tax Traditional IRA, конвертація частково оподатковується', 'Потребує щорічного відстеження і правильного оформлення', 'Форма 8606 обов\'язкова'],
    limit: '$7,000/рік ($8,000 якщо 50+)',
    bestFor: 'Дохід >$161k (single) або >$240k (married). Кроки: 1. Відкрийте Traditional IRA 2. Внесіть non-deductible $7k 3. Конвертуйте в Roth. Бажано зробити до кінця року без росту для уникнення оподаткування.',
  },
  {
    id: 'megabackdoor',
    icon: '🚀',
    name: 'Mega Backdoor Roth',
    fullName: 'Mega Backdoor Roth 401(k) Strategy',
    tag: 'ПРОСУНУТА СТРАТЕГІЯ',
    tagColor: '#ef4444',
    description: 'Дозволяє закинути до $46,500/рік в Roth через 401(k) після-податковий внесок + конвертацію. Але доступно не у всіх планах.',
    pros: ['До $46,500/рік додатково в Roth (на додаток до стандартних $23,500)', 'Великий Roth баланс без обмежень доходу', 'Ріст без податків на великі суми'],
    cons: ['Доступно тільки якщо 401(k) план дозволяє after-tax contributions + in-service withdrawals або in-plan Roth conversion', 'Складний процес, потребує консультації CPA', 'Більшість 401(k) планів НЕ підтримують'],
    limit: 'До $46,500/рік (загальний ліміт $69,000 мінус стандартні $23,500)',
    bestFor: 'High earners які вже максимізували всі інші рахунки. Перевірте чи підтримує ваш 401(k) — зателефонуйте у відділ HR або провайдеру плану.',
  },
]

export const BIASES: Bias[] = [
  {
    id: 'recency',
    icon: '🕐',
    name: 'Recency Bias',
    ua: 'Упередження нещодавності',
    description: 'Надаємо занадто велику вагу нещодавнім подіям і думаємо що вони тривватимуть вічно.',
    example: '"Ринок ріс 3 роки — буде рости вічно" (думали у 1999, 2007, 2021). "Ринок падає — буде падати завжди" (думали у березні 2009 і березні 2020 — обидва рази ідеальний момент для купівлі).',
    fix: 'Дивіться на 20–30-річну статистику, не на останні 12 місяців. Ринок завжди рухається циклами. Поточний тренд ≠ майбутній тренд.',
  },
  {
    id: 'loss_aversion',
    icon: '😰',
    name: 'Loss Aversion',
    ua: 'Страх втрат',
    description: 'Психологічно програш $100 болить вдвічі сильніше ніж радує виграш $100. Призводить до нераціональних рішень.',
    example: 'Продати після падіння 10% "щоб не втратити більше" → пропускаєте відновлення +50%. Або тримати збиткові акції роками — "якщо не продав, це ще не реальний збиток."',
    fix: 'Автоматизуйте інвестиції (auto-invest щомісяця). Не дивіться на рахунок частіше ніж раз в квартал під час просадок. Просадка = знижка, не збиток.',
  },
  {
    id: 'fomo',
    icon: '🚀',
    name: 'FOMO',
    ua: 'Fear of Missing Out',
    description: 'Страх пропустити "наступний великий ріст" штовхає купувати після того як актив вже виріс.',
    example: 'GameStop +2700% за тиждень → потім -90%. BTC листопад 2021 ($69k) → -77% через рік. NFT у 2022 → майже до нуля. Всі куплені більшістю ПІСЛЯ 500%+ росту.',
    fix: 'Якщо ви вже чули про "гарячий актив" від таксиста або в TikTok — швидше за все вже пізно. Нудна дисципліна > FOMO.',
  },
  {
    id: 'timing',
    icon: '⏰',
    name: 'Market Timing',
    ua: 'Спроба вгадати ринок',
    description: '"Зачекаю поки ринок впаде, потім куплю" — найдорожча фраза в інвестиціях.',
    example: 'Дослідження Fidelity: ті хто пропустив 10 найкращих днів S&P 500 за 20 років отримали ВДВІЧІ менший дохід. І 7 з 10 найкращих днів — у межах 15 днів від найгіршого.',
    fix: 'Time IN the market > timing the market. Є гроші — інвестуйте зараз. Можна розбити на 3–4 місяці якщо страшно, але не чекайте "кращого моменту" рік.',
  },
  {
    id: 'overconfidence',
    icon: '🦸',
    name: 'Overconfidence',
    ua: 'Самовпевненість',
    description: '80% водіїв вважають що кращі за середнього. 85% активних трейдерів впевнені що переграють ринок. Обидва помиляються.',
    example: '"Я проаналізував — Tesla точно виросте." Але ви конкуруєте з тисячами аналітиків і алгоритмами що аналізують ту саму інформацію з більшими ресурсами.',
    fix: 'Index funds + низькі комісії + час + дисципліна = краще ніж більшість активних стратегій. Це не порада — це статистика за 50+ років.',
  },
  {
    id: 'panic',
    icon: '📉',
    name: 'Panic Selling',
    ua: 'Продаж в паніці',
    description: 'Продати активи на просадці = реалізувати збиток і гарантовано пропустити відновлення.',
    example: 'Хто продав S&P 500 у березні 2020 (-34%) і "чекав стабільності" — пропустив +100% за наступні 18 місяців. Продали точно на дні і купили на +50% вище.',
    fix: 'Якщо дуже страшно під час просадки — ваш ризик-профіль занадто агресивний. Додайте бонди. Але при правильній алокації — просто не дивіться на рахунок.',
  },
  {
    id: 'anchoring',
    icon: '⚓',
    name: 'Anchoring Bias',
    ua: 'Якірне упередження',
    description: 'Прив\'язуємось до конкретної цифри (ціна купівлі, ATH) і приймаємо рішення відносно неї, а не відносно реальної вартості.',
    example: '"Я куплю Tesla назад коли вона повернеться до $400" (де ви купили). Або "S&P 500 був $5000, а зараз $4000 — це дешево!" (може бути і дорого залежно від фундаменталів).',
    fix: 'Ціна купівлі — ваша особиста психологічна якір, ринку на неї байдуже. Питайте: "Чи купив би я цей актив за поточною ціною зараз якби не тримав його?" Якщо ні — можливо варто переглянути.',
  },
  {
    id: 'disposition',
    icon: '🎭',
    name: 'Disposition Effect',
    ua: 'Ефект диспозиції',
    description: 'Продаємо активи що виросли (щоб "зафіксувати прибуток") і тримаємо збиткові (щоб "не визнавати збиток"). Рівно навпаки від оптимальної стратегії.',
    example: 'Apple виросла з $150 до $220 — "заберу прибуток". Rivian впала з $100 до $15 — "почекаю відновлення." Результат: продаєте переможців, тримаєте лузерів.',
    fix: 'Tax-loss harvesting — продавати збиткові позиції може бути вигідно (знижує податки). Переможців не треба продавати без причини. Рішення базуйте на перспективах, не на "вже заробив/програв."',
  },
  {
    id: 'confirmation',
    icon: '🔍',
    name: 'Confirmation Bias',
    ua: 'Упередження підтвердження',
    description: 'Шукаємо і запам\'ятовуємо тільки інформацію що підтверджує нашу вже існуючу думку. Ігноруємо протилежні аргументи.',
    example: 'Купили Bitcoin → читаєте тільки bullish статті про BTC, ігноруєте ризики. Вирішили що "ринок надто дорогий" → кожна погана новина підтверджує вашу думку, хороші ігноруєте.',
    fix: 'Активно шукайте протилежну думку (bull/bear case). Перед покупкою: прочитайте найсильніший аргумент ПРОТИ. Diversification — фізичний захист від confirmation bias через один актив.',
  },
  {
    id: 'herd',
    icon: '🐑',
    name: 'Herd Mentality',
    ua: 'Стадний інстинкт',
    description: 'Купуємо бо всі купують. Продаємо бо всі продають. Інстинкт безпеки в групі — але в інвестиціях веде до збитків.',
    example: 'Dot-com 2000: всі купували tech → крах -78%. GameStop 2021: WallStreetBets → крах -90%. Крипто 2021: "всі мої друзі заробляють" → BTC -77% у 2022.',
    fix: 'Contrarian principle: якщо ВСІ говорять що треба купувати — будьте обережні. Якщо ВСІ говорять що ринок мертвий — можливо ідеальний момент. Баффет: "Be fearful when others are greedy, greedy when others are fearful."',
  },
  {
    id: 'sunk_cost',
    icon: '🕳️',
    name: 'Sunk Cost Fallacy',
    ua: 'Помилка незворотних витрат',
    description: '"Вже стільки вклав — не можу продати." Тримаємо збиткову позицію бо вже "витратили" гроші і час на неї.',
    example: 'Купили акції Bed Bath & Beyond по $20. Впали до $5. "Вже вклав $10k, не продам в такий мінус." → компанія збанкрутувала, втратили все замість $7,500.',
    fix: 'Минулі витрати — незворотні і не мають впливати на майбутні рішення. Питання: "Якщо б у мене зараз були гроші з продажу, я б знову купив це?" Якщо ні — продайте і вкладіть в краще.',
  },
  {
    id: 'home_bias',
    icon: '🏠',
    name: 'Home Country Bias',
    ua: 'Упередження рідної країни',
    description: 'Інвестуємо переважно в компанії або активи рідної країни, бо вони "знайомі" і "зрозумілі". Це знижує диверсифікацію.',
    example: 'Американці тримають 80%+ в US акціях хоча США = 60% світового ринку. Українці, французи, японці — аналогічно. Японія у 1989 впала -80% і досі (у 2025!) нижче піку 36-річної давнини.',
    fix: '20–30% міжнародних акцій в портфелі (FZILX, VXUS) — простий захист від home country bias. Решта світу складає 40% глобального ринку і може показати кращі результати в майбутньому.',
  },
]

export const SCENARIOS = [
  { icon: '😬', title: 'S&P 500 на піку dot-com', year: '2000', asset: 'S&P 500', amount: 10000, result: 57000, note: 'Найгірший момент входу — все одно ×5.7 за 26 років' },
  { icon: '🎯', title: 'S&P 500 на дні 2009', year: '2009', asset: 'S&P 500', amount: 10000, result: 95000, note: 'Ідеальний момент — ×9.5 за 17 років' },
  { icon: '📈', title: 'S&P 500 у 2010', year: '2010', asset: 'S&P 500', amount: 10000, result: 75000, note: '×7.5 за 16 років — звичайний момент' },
  { icon: '🥇', title: 'Золото у 2000', year: '2000', asset: 'Gold', amount: 10000, result: 107000, note: '$280/oz → $2,950/oz = ×10.7 за 26 років' },
  { icon: '₿', title: 'Bitcoin у грудні 2017 (пік)', year: '2017', asset: 'Bitcoin', amount: 10000, result: 55000, note: 'Купили на піку $19k — все одно ×5.5 за 8 років (з -83% по дорозі)' },
  { icon: '💎', title: 'Bitcoin на дні 2022', year: '2022', asset: 'Bitcoin', amount: 10000, result: 62500, note: 'Купили на дні $16k — ×6.25 за 3 роки' },
]

// CAGR lookup for interactive what-if calculator
// S&P 500 approximate CAGR from Jan 1 of year to mid-2026 (total return)
export const SP500_CAGR: Record<number, number> = {
  2000: 0.070, 2001: 0.082, 2002: 0.098, 2003: 0.128, 2004: 0.122,
  2005: 0.118, 2006: 0.113, 2007: 0.108, 2008: 0.130, 2009: 0.168,
  2010: 0.135, 2011: 0.130, 2012: 0.140, 2013: 0.148, 2014: 0.132,
  2015: 0.126, 2016: 0.138, 2017: 0.142, 2018: 0.115, 2019: 0.196,
  2020: 0.163, 2021: 0.080, 2022: 0.095,
}

export const GOLD_CAGR: Record<number, number> = {
  2000: 0.100, 2001: 0.098, 2002: 0.112, 2003: 0.108, 2004: 0.105,
  2005: 0.094, 2006: 0.090, 2007: 0.086, 2008: 0.092, 2009: 0.088,
  2010: 0.055, 2011: 0.040, 2012: 0.038, 2013: 0.045, 2014: 0.048,
  2015: 0.082, 2016: 0.075, 2017: 0.070, 2018: 0.072, 2019: 0.078,
  2020: 0.138, 2021: 0.118, 2022: 0.270,
}

export const BTC_CAGR: Record<number, number> = {
  2016: 0.78, 2017: 0.35, 2018: 0.60, 2019: 0.55,
  2020: 0.50, 2021: 0.26, 2022: 0.83,
}
